stages:
    - deploy

deploy-dev:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script:
    - sudo cp -r ./* /data/vnwqi/
    - sudo chown -R vnwqi:vnwqi /data/vnwqi
    - sudo su vnwqi -c "cd /data/vnwqi; docker compose down || true; docker compose up --build -d"
    - echo "Successfully"
  tags:
    - dev-srv
  environment: develop
